
# .github/workflows/buildAndpublish.yml
name: Build and publish

on:
  push:
    tags:
    # must align with the tag-pattern configured on pub.dev, often just replace
      # {{version}} with [0-9]+.[0-9]+.[0-9]+
    #- 'V[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: 'v{{version}}'
    # If you prefer tags like '1.2.3', without the 'v' prefix, then use:
     - 'v[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: '{{version}}'
    # If your repository contains multiple packages consider a pattern like:
    # -

jobs:
  publish-python:
    if: false
    runs-on: ubuntu-latest
    name: PollinationAI_SDK Python   
    environment:
      name: pypi
      url: https://pypi.org/p/PollinationAI_SDK

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v4


      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Python Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          config-file: config.yml
          openapi-file: pollination_api.json

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Or whatever the version the package needs
      - name: Install build backend
        run: python -m pip install --upgrade pip build

      # Do something with the generated client (likely publishing it somewhere)
      - name: build python client
        run: |
          cd python-client
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python-client/dist/
  generate-dart:
    runs-on: ubuntu-latest
    name: PollinationAI_SDK Dart
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Dart Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
              generator: dart
              config-file: config.yml
              openapi-file: pollination_api.json
      - name: Perform Replacement
        run: |
          find dart-client/test -type f -name "*.dart" -exec sed -i 's/openapi/PollinationAI_SDK/g' {} +

  publish-dart:
    needs: generate-dart
    permissions:
      id-token: write
      contents: read
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: dart-client/
     