
# .github/workflows/buildAndpublish.yml
name: Build and publish to pub.dev

on:
  push:
    tags:
    # must align with the tag-pattern configured on pub.dev, often just replace
      # {{version}} with [0-9]+.[0-9]+.[0-9]+
    #- 'V[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: 'v{{version}}'
    # If you prefer tags like '1.2.3', without the 'v' prefix, then use:
     - 'v[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: '{{version}}'
    # If your repository contains multiple packages consider a pattern like:
    # -

jobs:
  generate-client:
    runs-on: ubuntu-latest
    name: Example   
    environment:
      name: pypi
      url: https://pypi.org/p/Credit-Management
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Python Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          config-file: config.yml
          openapi-file: pollination_api.json

      # Do something with the generated client (likely publishing it somewhere)
      - name: Do something with the client
        run: |
          ls